In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('./'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also writ

./.amlignore
./.amlignore.amltmp
./0.99.ipynb
./0.99.ipynb.amltmp
./0.99_orig.ipynb
./0.99_orig.ipynb.amltmp
./plot.ipynb
./plot.ipynb.amltmp
./predictions.csv
./substances.csv
./test.csv
./train.csv
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-18-20-34-41Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-18-21-43-44Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-18-22-31-27Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-18-22-34-50Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-18-22-35-3Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-19-11-31-26Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-19-13-2-6Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-19-14-16-15Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-19-15-18-37Z.ipynb
./.ipynb_aml_checkpoints/0.99-checkpoint2024-11-19-8-21-51Z.ipynb
./.ipynb_aml_checkpoints/0.99_orig-checkpoint2024-11-19-11-27-33Z.ipynb
./.ipynb_aml_checkpoints/0.99_orig-checkpoint2024-11-19-11-33-

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from sklearn.model_selection import GridSearchCV, cross_val_score, RandomizedSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.decomposition import PCA
from torch.utils.data import TensorDataset, DataLoader
from scipy.stats import uniform, randint, loguniform
from sklearn import preprocessing

import warnings
warnings.filterwarnings("ignore")

In [3]:
data_train = pd.read_csv("./train.csv")
data_test = pd.read_csv("./test.csv")

X_train = data_train.iloc[:, 6:].values
X_test = data_test.iloc[:, 5:].values

In [4]:
data_train

sample_name device_serial  substance_form_display  \
0            11140009    M1-1000112      Homogenized Powder   
1     22.0401-P002.02    M1-1000109  Non homogenized powder   
2     22.0117-P001.02    M1-1000100  Non homogenized powder   
3        20.0163-P009      N1-00196             Unspecified   
4        19.0286-P005      N1-00196             Unspecified   
...               ...           ...                     ...   
1295  22.0267-P001.01    M1-1000100      Homogenized Powder   
1296         11060000    M1-1000144      Homogenized Powder   
1297     22.0368-P002    M1-1000130      Homogenized Powder   
1298  22.0342-P002.04    M1-1000109      Homogenized Powder   
1299  22.0401-P001.04    M1-1000109      Homogenized Powder   

     measure_type_display prod_substance     PURITY     908.1     914.3  \
0          Direct contact         Heroin  58.500000  0.044734  0.042720   
1          Direct contact         Heroin  18.600000  0.063695  0.056980   
2          Direct contact         Heroin  19.881719  0.050358  0.044910   
3          Direct contact         Heroin  52.500000  0.525050  0.520434   
4          Direct contact         Heroin  48.900000  0.479365  0.467401   
...                   ...            ...        ...       ...       ...   
1295       Direct contact         Heroin  10.100000  0.107930  0.103983   
1296       Direct contact         Heroin  44.900000  0.040564  0.041559   
1297       Direct contact         Heroin  53.400000  0.106459  0.108084   
1298       Direct contact         Heroin  13.600000  0.075628  0.068853   
1299       Direct contact         Heroin  19.600000  0.058483  0.051543   

         920.5     926.7  ...    1620.5    1626.6    1632.8      1639  \
0     0.041361  0.040055  ...  0.003972  0.007906  0.012490  0.018123   
1     0.050080  0.043339  ...  0.093002  0.099668  0.108805  0.117120   
2     0.039148  0.033730  ...  0.083369  0.090485  0.100462  0.109033   
3     0.517187  0.516377  ...  0.357223  0.370060  0.386062  0.404460   
4     0.456680  0.446148  ...  0.350973  0.366094  0.384536  0.405034   
...        ...       ...  ...       ...       ...       ...       ...   
1295  0.100068  0.096422  ...  0.133917  0.138535  0.145144  0.151008   
1296  0.042435  0.043870  ... -0.007995 -0.004902 -0.001237  0.003390   
1297  0.109983  0.109541  ...  0.052178  0.056051  0.060666  0.066257   
1298  0.062538  0.056079  ...  0.094620  0.101527  0.111090  0.119861   
1299  0.044479  0.037586  ...  0.082725  0.089156  0.097976  0.106049   

        1645.2    1651.4    1657.6    1663.8      1670    1676.2  
0     0.025070  0.033235  0.042502  0.052237  0.061383  0.068823  
1     0.121947  0.125137  0.128688  0.133501  0.138187  0.140248  
2     0.113411  0.117053  0.121665  0.128366  0.134636  0.136961  
3     0.425567  0.450527  0.479066  0.508943  0.539349  0.564486  
4     0.426582  0.450564  0.477045  0.504142  0.531764  0.553650  
...        ...       ...       ...       ...       ...       ...  
1295  0.153738  0.155602  0.158525  0.163138  0.167623  0.169048  
1296  0.009303  0.016472  0.023843  0.031736  0.039568  0.046056  
1297  0.073435  0.083057  0.094621  0.106288  0.117307  0.126626  
1298  0.124868  0.128340  0.132605  0.138737  0.144825  0.148246  
1299  0.110971  0.114777  0.119445  0.125784  0.132106  0.135891  

[1300 rows x 131 columns]

In [5]:
pca = PCA()
pca.fit(X_train)
cumvariance = np.cumsum(pca.explained_variance_ratio_)
cumvariance

array([0.86338598, 0.98281272, 0.99711247, 0.99910158, 0.99959773,
       0.99975821, 0.99985687, 0.99990601, 0.99993958, 0.99995823,
       0.99997198, 0.99998013, 0.99998455, 0.9999882 , 0.99999078,
       0.99999284, 0.99999461, 0.99999564, 0.99999645, 0.9999971 ,
       0.99999753, 0.99999789, 0.99999824, 0.9999985 , 0.99999873,
       0.99999892, 0.99999902, 0.99999913, 0.99999921, 0.99999929,
       0.99999934, 0.9999994 , 0.99999944, 0.99999948, 0.99999952,
       0.99999955, 0.99999958, 0.99999961, 0.99999963, 0.99999966,
       0.99999968, 0.9999997 , 0.99999972, 0.99999974, 0.99999975,
       0.99999977, 0.99999978, 0.9999998 , 0.99999981, 0.99999982,
       0.99999983, 0.99999984, 0.99999985, 0.99999986, 0.99999987,
       0.99999988, 0.99999988, 0.99999989, 0.9999999 , 0.9999999 ,
       0.99999991, 0.99999991, 0.99999992, 0.99999992, 0.99999993,
       0.99999993, 0.99999994, 0.99999994, 0.99999994, 0.99999995,
       0.99999995, 0.99999995, 0.99999995, 0.99999996, 0.99999

In [ ]:
# keep 99% of variance
#n_comp = np.where(cumvariance>0.99)[0][0]
#n_comp

In [ ]:
# pure = pd.read_csv("./substances.csv")
# #pure = pure[pure["substance"].str.contains("heroin")]
# pure = pure.iloc[:,1:].values
# pure.shape

In [ ]:
# X_normalized = preprocessing.normalize(X_train, axis=1)
# pure_normalized = preprocessing.normalize(pure, axis=1)

In [ ]:
# X_normalized.shape

In [ ]:
# X_normalized = X_normalized @ pure_normalized.T
# X_normalized.shape

In [ ]:
# pca = PCA()
# pca.fit(X_normalized)
# np.cumsum(pca.explained_variance_ratio_)

In [6]:
y = data_train.iloc[:,5:6].values/100
y.shape

(1300, 1)

In [7]:

seed = 43
"""
# Combine original data with PCA components
standardizer = StandardScaler()
X_st = standardizer.fit_transform(X_train)
"""
## Perform PCA to retain 99% of the variance
pca = PCA()
pca.fit(X_train)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

#X_normalized = preprocessing.normalize(X_pca)
#X_normalized = X_train


# Standardisation des données (avant PCA)
#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

#X_train, X_valid, y_train, y_valid = train_test_split(X_normalized, y, test_size=0.2, random_state = 42)

# Convert to tensors
#X_train_tensor = torch.tensor(X_train, dtype=torch.float32).clone().detach()
#y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).reshape(-1, 1).clone().detach()
#X_valid_tensor = torch.tensor(X_valid, dtype=torch.float32).clone().detach()
#y_valid_tensor = torch.tensor(y_valid.values, dtype=torch.float32).reshape(-1, 1).clone().detach()

In [8]:
X_train

array([[-4.70200365e-01, -3.83971275e-01,  3.78512968e-02, ...,
        -1.54638703e-05,  2.61830668e-06,  2.29016815e-06],
       [-2.47416291e-01, -5.47927097e-02, -8.79727127e-02, ...,
         4.79866179e-06, -1.01758180e-05,  1.87281627e-06],
       [-3.28515012e-01, -6.35064321e-02, -7.65174225e-02, ...,
        -7.73878857e-06, -2.67699877e-05,  6.73251349e-06],
       ...,
       [ 1.47048873e-01, -4.41047301e-01,  4.97612111e-02, ...,
         5.23901569e-06,  4.25810056e-06, -1.69010730e-05],
       [-1.99482391e-01, -6.61147111e-02, -5.80451993e-02, ...,
         1.25530178e-05, -7.16188076e-07,  3.36811338e-06],
       [-3.21640088e-01, -6.43204801e-02, -7.81904136e-02, ...,
         1.00189269e-06, -9.71338417e-06, -4.73784684e-06]])

In [10]:
y_train = y
y_train

array([[0.585     ],
       [0.186     ],
       [0.19881719],
       ...,
       [0.534     ],
       [0.136     ],
       [0.196     ]])

In [ ]:
#X_pca = pca.transform(X_test)
#X_test_normalized = preprocessing.normalize(X_pca)
#X_test_normalized = X_test
#X_test_tensor = torch.tensor(X_test_normalised, dtype=torch.float32).clone().detach() 

# X_test_normalized = preprocessing.normalize(X_test.values, axis=1)
# X_test_normalized = X_test_normalized @ pure_normalized.T
# X_test_normalized.shape

In [11]:
def my_loss(output, target):
    loss = torch.maximum(torch.zeros_like(output),(output - target)-.05) + torch.maximum(torch.zeros_like(output),(target - output)-.05)
    return torch.mean(loss)

In [56]:
# Définir le modèle de réseau de neurones simple

class FeedForwardNN(nn.Module):

    def __init__(self, input_size, lin_layer_sizes,

                 outpout_size, lin_layer_dropouts, activation):
        super().__init__()       
        if activation == 0:
            self.activation = nn.ReLU()
        elif activation == 1:
            self.activation = nn.SiLU()
        elif activation == 2:
            self.activation = nn.Tanh()
        elif activation == 3:
            self.activation = nn.LeakyReLU()  

        # Linear Layers
        first_lin_layer = nn.Linear(input_size, lin_layer_sizes[0])
        self.lin_layers = nn.ModuleList([first_lin_layer] + [nn.Linear(lin_layer_sizes[i], lin_layer_sizes[i + 1]) for i in range(len(lin_layer_sizes) - 1)])     

        # Output Layer
        self.outpout_layer = nn.Linear(lin_layer_sizes[-1], outpout_size)
        
        # Dropout Layers
        self.dropout_layers = nn.ModuleList([nn.Dropout(rate) for rate,size in zip(lin_layer_dropouts,lin_layer_sizes)])

    def forward(self, x):
        for lin_layer, dropout_layer in zip(self.lin_layers, self.dropout_layers):
            x = lin_layer(x)     
            x = self.activation(x)
            x = dropout_layer(x)
 
        x = self.outpout_layer(x)
        x = nn.Sigmoid()(x)
  
        return x

# Définir la classe NeuralNetRegressor
class NeuralNetRegressor(BaseEstimator, RegressorMixin):

    def __init__(self, input_size, random_state, eta=0.001, max_epochs=100, batch=10, lin_layer_sizes = [50, 50],
            outpout_size = 1, lin_layer_dropouts = [0.4, 0.4], activation = 0, loss=0, n_comp=None):

        if n_comp is not None:
            print("n_comp", n_comp)
            self.input_size = n_comp
        else:
            self.input_size = input_size

        self.random_state = random_state
        self.eta = eta
        self.max_epochs = max_epochs
        self.batch = batch
        self.lin_layer_sizes = lin_layer_sizes
        self.outpout_size = outpout_size
        self.lin_layer_dropouts = lin_layer_dropouts
        self.activation = activation
        self.model = None

        self.n_comp = n_comp

        self.loss = loss
        if loss==0:
            self.criterion = nn.MSELoss()
        elif loss==1:
            self.criterion = nn.L1Loss()
        else:
            self.criterion = my_loss
       
    def fit(self, X, y, do_print=False,X_valid=None, y_valid=None ):
        #print("self.eta",self.eta)
        #print("X",X.shape)
        #print("Y",y.shape)

        #print("FITTING")

        self.model = FeedForwardNN(self.n_comp, self.lin_layer_sizes,
                 self.outpout_size, self.lin_layer_dropouts, self.activation)


        #print("n_comp", self.n_comp)
        if self.n_comp is not None:
            X = X[:,:self.n_comp]

        #print("shape", X.shape)
        
        #print("model", self.model)

        optimizer = optim.Adam(self.model.parameters(), lr=self.eta)
        X_tensor = torch.tensor(X).clone().detach().float()
        y_tensor = torch.tensor(y).clone().detach().float()
        dataset = TensorDataset(X_tensor, y_tensor)
        dataloader = DataLoader(dataset, batch_size=self.batch, shuffle=True)
        self.model.train()

        if X_valid is not None:
            X_valid = torch.tensor(X_valid).clone().detach().float()
            y_valid = torch.tensor(y_valid).clone().detach().float()

        # Training loop
        for epoch in range(self.max_epochs):

            epoch_loss = 0.0
            for batch_X, batch_y in dataloader:
                optimizer.zero_grad()  # Reset gradients
                outputs = self.model(batch_X)  # Forward pass
                loss = self.criterion(outputs, batch_y)  # Compute loss
                loss.backward()  # Backward pass
                optimizer.step()  # Update parameters
                epoch_loss += loss.item()
            if do_print and X_valid is not None:
                outputs = self.model(X_valid)  # Forward pass
                valid_loss = self.criterion(outputs, y_valid)  # Compute loss
                print(f"Epoch {epoch+1}/{self.max_epochs}, Loss: {epoch_loss / len(dataloader)}, Valid_loss: {valid_loss}")

            elif do_print:
                print(f"Epoch {epoch+1}/{self.max_epochs}, Loss: {epoch_loss / len(dataloader)}")

        return self  

    def predict(self, X):
        self.model.eval()
        print("n_comp", self.n_comp)
        if self.n_comp is not None:
            X = X[:,:self.n_comp]

        X_tensor = torch.tensor(X, dtype=torch.float32)
        with torch.no_grad():
            outputs = self.model(X_tensor)
        return outputs.numpy()
        
    def parameters(self):
        return self.model.parameters()

In [13]:
class RandomLayers:
    def __init__(self,min_layers, max_layers, min_nodes, max_nodes):
        self.min_nodes = min_nodes
        self.max_nodes = max_nodes
        self.min_layers = min_layers
        self.max_layers = max_layers

    def rvs(self, random_state=None):
        if random_state is not None:
            prev = randint.random_state
            randint.random_state = random_state 

        nodes = randint.rvs(self.min_nodes, self.max_nodes)
        res = [nodes for _ in range(randint.rvs(self.min_layers, self.max_layers))]

        if random_state is not None:
            randint.random_state = prev

        return res

In [14]:
class RandomDropout:
    def __init__(self, max_layers,min_dropout,max_dropout):
        self.min_dropout = min_dropout
        self.max_dropout = max_dropout
        self.max_layers = max_layers

    def rvs(self, random_state=None):
        if random_state is not None:
            prev = uniform.random_state
            uniform.random_state = random_state 
        dropout = uniform.rvs(self.min_dropout, self.max_dropout)
        res = [dropout for _ in range(self.max_layers)]

        if random_state is not None:
            uniform.random_state = prev

        return res

In [15]:

def my_custom_score(ground_truth, predictions):
    return np.mean(np.abs(predictions-ground_truth)*100<=5)


from sklearn.metrics import make_scorer

scorer = make_scorer(my_custom_score, greater_is_better=True)

In [28]:
X_train[:,:3]

array([[-0.47020036, -0.38397127,  0.0378513 ],
       [-0.24741629, -0.05479271, -0.08797271],
       [-0.32851501, -0.06350643, -0.07651742],
       ...,
       [ 0.14704887, -0.4410473 ,  0.04976121],
       [-0.19948239, -0.06611471, -0.0580452 ],
       [-0.32164009, -0.06432048, -0.07819041]])

In [44]:
# Initialiser le modèle

seed = 42
np.random.seed(seed)
torch.manual_seed(seed)
input_size = X_train.shape[1]
net = NeuralNetRegressor(input_size=input_size, random_state=seed)

max_layers = 5

# Définir les paramètres pour GridSearch
params_dist = {

    'eta': loguniform(1e-4, 1e-1),
    'max_epochs': randint(10, 500),
    'batch': randint(8, 64),
    'lin_layer_sizes': RandomLayers(1,max_layers,4,256),  # Taille de 1 à 4 couches, entre 4 et 256 neurones par couche
    'lin_layer_dropouts': RandomDropout(max_layers,0.,.5),
    'activation': randint(0, 4),
    'loss': randint(0, 3),
    'n_comp': randint(1, X_train.shape[1]),
}

# Initialiser RandomizedSearchCV
random_search = RandomizedSearchCV(net, params_dist, refit=True, cv=5, random_state=seed, scoring=scorer, verbose=3, n_iter=30, n_jobs=-2)

# Entraîner le modèle avec GridSearch
random_grid_result = random_search.fit(X_train, y_train)
nouveau_model = random_grid_result.best_estimator_
print("Best score: %f using %s" % (random_grid_result.best_score_, random_grid_result.best_params_))

Fitting 5 folds for each of 30 candidates, totalling 150 fits
FITTING
n_comp 53
shape (1040, 53)
model FeedForwardNN(
  (activation): Tanh()
  (lin_layers): ModuleList(
    (0): Linear(in_features=53, out_features=107, bias=True)
    (1-3): 3 x Linear(in_features=107, out_features=107, bias=True)
  )
  (outpout_layer): Linear(in_features=107, out_features=1, bias=True)
  (dropout_layers): ModuleList(
    (0-3): 4 x Dropout(p=0.16685430556951092, inplace=False)
  )
)
n_comp 53
[CV 3/5] END activation=2, batch=18, eta=0.0023864188780056052, lin_layer_dropouts=[0.16685430556951092, 0.16685430556951092, 0.16685430556951092, 0.16685430556951092, 0.16685430556951092], lin_layer_sizes=[107, 107, 107, 107], loss=2, max_epochs=159, n_comp=53;, score=0.935 total time=  35.5s
FITTING
n_comp 89
shape (1040, 89)
model FeedForwardNN(
  (activation): ReLU()
  (lin_layers): ModuleList(
    (0): Linear(in_features=89, out_features=76, bias=True)
    (1-2): 2 x Linear(in_features=76, out_features=76, bi

In [53]:
# from matplotlib import pyplot as plt
# def plot_search_results(grid):
#     """
#     Params: 
#         grid: A trained GridSearchCV object.
#     """
#     ## Results from grid search
#     results = grid.cv_results_
#     means_test = results['mean_test_score']
#     stds_test = results['std_test_score']
#     #means_train = results['mean_train_score']
#     #stds_train = results['std_train_score']

#     ## Getting indexes of values per hyper-parameter
#     masks=[]
#     masks_names= list(grid.best_params_.keys())
#     for p_k, p_v in grid.best_params_.items():
#         masks.append(list(results['param_'+p_k].data==p_v))

#     params=grid.param_grid

#     ## Ploting results
#     fig, ax = plt.subplots(1,len(params),sharex='none', sharey='all',figsize=(20,5))
#     fig.suptitle('Score per parameter')
#     fig.text(0.04, 0.5, 'MEAN SCORE', va='center', rotation='vertical')
#     pram_preformace_in_best = {}
#     for i, p in enumerate(masks_names):
#         m = np.stack(masks[:i] + masks[i+1:])
#         pram_preformace_in_best
#         best_parms_mask = m.all(axis=0)
#         best_index = np.where(best_parms_mask)[0]
#         x = np.array(params[p])
#         y_1 = np.array(means_test[best_index])
#         e_1 = np.array(stds_test[best_index])
#         #y_2 = np.array(means_train[best_index])
#         #e_2 = np.array(stds_train[best_index])
#         ax[i].errorbar(x, y_1, e_1, linestyle='--', marker='o', label='test')
#         #ax[i].errorbar(x, y_2, e_2, linestyle='-', marker='^',label='train' )
#         ax[i].set_xlabel(p.upper())

#     plt.legend()
#     plt.show()

FITTING
n_comp 76
shape (1040, 76)
model FeedForwardNN(
  (activation): SiLU()
  (lin_layers): ModuleList(
    (0): Linear(in_features=76, out_features=195, bias=True)
    (1-3): 3 x Linear(in_features=195, out_features=195, bias=True)
  )
  (outpout_layer): Linear(in_features=195, out_features=1, bias=True)
  (dropout_layers): ModuleList(
    (0-3): 4 x Dropout(p=0.10616955533913808, inplace=False)
  )
)
n_comp 76
[CV 1/5] END activation=1, batch=31, eta=0.031428808908401086, lin_layer_dropouts=[0.10616955533913808, 0.10616955533913808, 0.10616955533913808, 0.10616955533913808, 0.10616955533913808], lin_layer_sizes=[195, 195, 195, 195], loss=0, max_epochs=170, n_comp=76;, score=0.012 total time=  31.6s
FITTING
n_comp 64
shape (1040, 64)
model FeedForwardNN(
  (activation): LeakyReLU(negative_slope=0.01)
  (lin_layers): ModuleList(
    (0): Linear(in_features=64, out_features=193, bias=True)
    (1-2): 2 x Linear(in_features=193, out_features=193, bias=True)
  )
  (outpout_layer): Line

In [54]:
# plot_search_results(random_search)

TypeError: 'bool' object is not iterable

In [55]:
random_search.best_params_.items()

dict_items([('activation', 3), ('batch', 23), ('eta', 0.0004992453416923981), ('lin_layer_dropouts', [0.0453032172664104, 0.0453032172664104, 0.0453032172664104, 0.0453032172664104, 0.0453032172664104]), ('lin_layer_sizes', [193, 193, 193]), ('loss', 2), ('max_epochs', 253), ('n_comp', 64)])

In [ ]:
# nnreg = NeuralNetRegressor(input_size=input_size, random_state=55, **random_grid_result.best_params_)
# nnreg.fit(X_train, y_train,do_print=True, X_valid=X_valid, y_valid=y_valid )

In [ ]:
# nnreg.model.eval()
# y_pred = nnreg.model(torch.tensor(X_valid).float())

# #np.mean(np.square(y_valid-y_pred))

In [ ]:
# y_pred2 = nnreg.predict(X_valid)
# y_pred2 - y_pred.detach().numpy()[:,0]


In [ ]:
# loss = nn.MSELoss()
# loss(torch.tensor(y_valid),torch.tensor(y_pred))

In [57]:
#y_pred = nouveau_model.predict(X_valid)
y_pred_train = nouveau_model.predict(X_train)
predictions = nouveau_model.predict(X_test)*100

# Vérifiez les sorties du modèle
print("y_pred contains NaN:", np.isnan(predictions).any())



# Calculer le t_score
train_score = np.mean(np.abs(y_pred_train-y_train)*100<=5)
print("t_score train :", train_score)

ids = np.arange(1, len(predictions) + 1)

# Create a DataFrame for the output
output_df = pd.DataFrame({

    'ID': ids,

    'PURITY': predictions[:,0]

})

# Save the DataFrame to a CSV file
output_df.to_csv('predictions.csv', index=False)

n_comp 64
n_comp 64
y_pred contains NaN: False
t_score train : 1.0


In [58]:
y_pred_train

array([[0.5839623 ],
       [0.17583114],
       [0.18533981],
       ...,
       [0.516559  ],
       [0.15392096],
       [0.19709522]], dtype=float32)

In [59]:
y_train

array([[0.585     ],
       [0.186     ],
       [0.19881719],
       ...,
       [0.534     ],
       [0.136     ],
       [0.196     ]])